import { create } from 'zustand';
import {
  signInWithPopup,
  signInWithCustomToken,
  signOut as firebaseSignOut,
  onAuthStateChanged,
  User as FirebaseUser,
} from 'firebase/auth';
import { doc, getDoc, setDoc, serverTimestamp } from 'firebase/firestore';
import { auth, db, googleProvider } from '@/lib/firebase';
import type { User, UserSettings, StreakData } from '@/types';

// Check if running in Electron
const isElectron = typeof window !== 'undefined' && window.electronAPI?.isElectron;

interface AuthState {
  user: User | null;
  firebaseUser: FirebaseUser | null;
  loading: boolean;
  error: string | null;
  signInWithGoogle: () => Promise<void>;
  signOut: () => Promise<void>;
  updateUserSettings: (settings: Partial<UserSettings>) => Promise<void>;
  updateStreak: (streak: Partial<StreakData>) => Promise<void>;
  initialize: () => () => void;
}

const defaultSettings: UserSettings = {
  dailyReminderTime: '09:00',
  weekStartsOn: 'monday',
  theme: 'dark',
  notifications: {
    enabled: false,
    firstReminderHours: 24,
    secondReminderHours: 1,
  },
};

const defaultStreak: StreakData = {
  current: 0,
  longest: 0,
  lastCompletedDate: '',
};

export const useAuthStore = create<AuthState>((set, get) => ({
  user: null,
  firebaseUser: null,
  loading: true,
  error: null,

  initialize: () => {
    console.log('[AuthStore] Initializing auth listener...');
    console.log('[AuthStore] isElectron:', typeof window !== 'undefined' && window.electronAPI?.isElectron);

    const unsubscribe = onAuthStateChanged(auth, async (firebaseUser) => {
      console.log('[AuthStore] Auth state changed, user:', firebaseUser ? firebaseUser.uid : 'null');
      if (firebaseUser) {
        try {
          console.log('[AuthStore] Fetching user doc...');
          const userDoc = await getDoc(doc(db, 'users', firebaseUser.uid));
          console.log('[AuthStore] User doc fetched, exists:', userDoc.exists());

          if (userDoc.exists()) {
            console.log('[AuthStore] Setting user state with existing doc');
            set({
              user: { id: firebaseUser.uid, ...userDoc.data() } as User,
              firebaseUser,
              loading: false,
              error: null,
            });
            console.log('[AuthStore] User state set, loading: false');
          } else {
            console.log('[AuthStore] Creating new user document...');
            // Create new user document
            const newUser: Omit<User, 'id'> = {
              email: firebaseUser.email || '',
              displayName: firebaseUser.displayName || 'User',
              createdAt: serverTimestamp() as any,
              settings: defaultSettings,
              streak: defaultStreak,
            };

            await setDoc(doc(db, 'users', firebaseUser.uid), newUser);
            console.log('[AuthStore] New user doc created');

            set({
              user: { id: firebaseUser.uid, ...newUser } as User,
              firebaseUser,
              loading: false,
              error: null,
            });
            console.log('[AuthStore] User state set with new doc, loading: false');
          }
        } catch (error) {
          console.error('[AuthStore] Error fetching user:', error);
          set({ loading: false, error: 'Failed to load user data' });
        }
      } else {
        console.log('[AuthStore] No user, setting loading: false');
        set({ user: null, firebaseUser: null, loading: false, error: null });
      }
    });

    // Set up Electron auth callback listener (only once)
    if (typeof window !== 'undefined' && window.electronAPI?.isElectron && window.electronAPI?.onAuthCallback) {
      console.log('[AuthStore] Setting up Electron auth callback listener');
      window.electronAPI.onAuthCallback(async (data) => {
        console.log('[Auth] Received auth callback from Electron');
        try {
          // Sign in with custom token (generated by Cloud Function)
          await signInWithCustomToken(auth, data.customToken);
          console.log('[Auth] Successfully signed in via Electron with custom token');
        } catch (error: any) {
          console.error('[Auth] Error signing in with custom token:', error);
          set({ error: error.message, loading: false });
        }
      });
    }

    return unsubscribe;
  },

  signInWithGoogle: async () => {
    try {
      set({ loading: true, error: null });

      if (isElectron && window.electronAPI?.startGoogleAuth) {
        // In Electron: Open auth in system browser (supports passkey)
        console.log('[Auth] Starting Electron auth flow...');
        await window.electronAPI.startGoogleAuth();
        // Don't set loading to false - wait for callback
        // The auth callback listener will handle the token
      } else {
        // Standard web popup auth
        await signInWithPopup(auth, googleProvider);
      }
    } catch (error: any) {
      console.error('Sign in error:', error);
      set({ error: error.message, loading: false });
    }
  },

  signOut: async () => {
    try {
      await firebaseSignOut(auth);
      set({ user: null, firebaseUser: null });
    } catch (error: any) {
      console.error('Sign out error:', error);
      set({ error: error.message });
    }
  },

  updateUserSettings: async (settings) => {
    const { user, firebaseUser } = get();
    if (!user || !firebaseUser) return;

    try {
      const updatedSettings = { ...user.settings, ...settings };
      await setDoc(
        doc(db, 'users', firebaseUser.uid),
        { settings: updatedSettings },
        { merge: true }
      );
      set({ user: { ...user, settings: updatedSettings } });
    } catch (error: any) {
      console.error('Error updating settings:', error);
      set({ error: error.message });
    }
  },

  updateStreak: async (streak) => {
    const { user, firebaseUser } = get();
    if (!user || !firebaseUser) return;

    try {
      const updatedStreak = { ...user.streak, ...streak };
      await setDoc(
        doc(db, 'users', firebaseUser.uid),
        { streak: updatedStreak },
        { merge: true }
      );
      set({ user: { ...user, streak: updatedStreak } });
    } catch (error: any) {
      console.error('Error updating streak:', error);
      set({ error: error.message });
    }
  },
}));
